services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    networks:
      - net-back

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 30s
      start_interval: 3s


  frontend:
    image: nginx
    volumes:
      - ./content:/usr/share/nginx/html
      - ./configs:/etc/nginx/conf.d
    ports:
      - "8081:80"
    networks:
      - net-back
    depends_on:
      backend:
        condition: service_healthy



  backend:
    build: .
    ports:
      - "8089:8089"

    volumes:
    - .:/app

    networks:
      - net-front
      - net-back

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/health"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 30s
      start_interval: 3s

    depends_on:
      redis:
        condition: service_healthy

  worker:
    build: .
    working_dir: /app
    command: celery -A nhl_match_prediction.tasks.celery_app:celery_app worker --loglevel=info -E
    volumes:
      - .:/app
    networks:
      - net-back
    depends_on:
      - redis
      - backend
    environment:
      - PYTHONPATH=/app

  flower:
    image: mher/flower
    command: >
      sh -c "sleep 5 && celery --broker=redis://redis:6379/0 flower --port=5555"
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - worker
    networks:
      - net-back




volumes:
  redis-volume:


networks:
  net-front:

  net-back:
