services:
  redis:
    image: redis
    # ports:
    #   - "6379:6379"
    volumes:
      - redis-volume:/data
    networks:
      - net-back

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 30s
      #start_interval: 3s


  frontend:
    image: nginx
    volumes:
      - ./content:/usr/share/nginx/html
      - ./configs:/etc/nginx/conf.d:ro  # read-only
    ports:
      - "8081:80"
    networks:
      - net-back
    depends_on:
      backend:
        condition: service_healthy



  backend:
    build: .
    env_file:
      - .env
    ports:
      - "8089:8089"

    volumes:
    - .:/app

    networks:
      - net-front
      - net-back

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/health"]
      interval: 10s
      timeout: 2s
      retries: 5
      start_period: 30s
      #start_interval: 3s

    depends_on:
      # db-init:
      #   condition: service_completed_successfully
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy

  # worker:
  #   build: .
  #   working_dir: /app
  #   command: celery -A nhl_match_prediction.tasks.celery_app:celery_app worker --loglevel=info -E
  #   volumes:
  #     - .:/app
  #   networks:
  #     - net-back
  #   depends_on:
  #     - redis
  #     - backend
  #   env_file:
  #     - .env
  #   environment:
  #     - PYTHONPATH=/app

  # beat:
  #   build: .
  #   command: celery -A nhl_match_prediction.tasks.celery_app:celery_app beat --loglevel=info
  #   volumes:
  #     - .:/app
  #   networks:
  #     - net-back
  #   env_file:
  #     - .env
  #   environment:
  #     - PYTHONPATH=/app

  # bot:
  #   build: .
  #   command: python bot.py
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app
  #   networks:
  #     - net-back
  #   depends_on:
  #     - backend
  #     - redis
  #   environment:
  #     - PYTHONPATH=/app

  # flower:
  #   image: mher/flower
  #   command: >
  #     sh -c "sleep 5 && celery --broker=redis://redis:6379/0 flower --port=5555"
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - redis
  #     - worker
  #   networks:
  #     - net-back

  postgres:
    image: postgres:15
    container_name: nhl_postgres
    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nhl_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - net-back

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5


  db-init:
    build: .
    volumes:
      - .:/app
    command: python -m nhl_match_prediction.etl_pipeline.init_db
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - net-back




volumes:
  redis-volume:
  postgres_data:


networks:
  net-front:

  net-back:
