apiVersion: v1
kind: Service
metadata:
  name: nhl-backend-service
spec:
  type: NodePort
  selector:
    app: nhl-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8089
      nodePort: 30007
