defaults:
  - _self_

date:
  start: 2026-02-01
  end: 2026-02-08

pipeline:
  fail_fast: false
  log_level: INFO

steps:
  collect_raw: true
  collect_standings: true
  build_features: true
  json_to_csv: true
  load_sqlite: true

hydra:
  run:
    dir: .
  output_subdir: null
