defaults:
  - _self_

date:
  start: 2026-04-14
  end: 2026-05-05

pipeline:
  fail_fast: true
  log_level: INFO
  mode: full  # или incremental


steps:
  collect_raw: true
  collect_standings: true


  build_pbp_features: true
  json_to_postgres: true

  build_xg_game_dataset: true

  build_games_with_features: true
  build_standings_daily_features: true
  build_goalie_features: true
  build_player_features: true

  # load_sqlite: true
  build_match_features: false
  build_future_games_features: false
  build_upcoming_match_features: false
  export_match_features: false



hydra:
  run:
    dir: .
  output_subdir: null
