defaults:
  - _self_

date:
  start: 2026-03-28
  end: 2026-04-30

pipeline:
  fail_fast: true
  log_level: INFO

steps:
  collect_raw: false
  collect_standings: false
  build_features: false
  json_to_csv: false

  build_games_with_features: false
  standings_features: false
  build_goalie_features: false
  build_player_features: false

  load_sqlite: false
  build_match_features: true
  build_future_games_features: true
  build_upcoming_match_features: true
  export_match_features: true



hydra:
  run:
    dir: .
  output_subdir: null
